In [1]:
import csv
import pandas as pd
import numpy as np
import os
import json

In [2]:
file_path="Community_Health_Indicator_Reports__CHIRS___Latest_Data.csv"

health_stats=pd.read_csv(file_path)

In [3]:
health_stats.head()

,County Name,Health Topic Number,Health Topic,Indicator Number,Indicator,Event Count,Average Number of Denominator,Measure Unit,Percent/Rate,Lower Limit of 95% CI,Upper Limit of 95% CI,Data Comments,Quartile,Data Years,Data Source,Mapping Distribution,Location
0,Mohawk Valley,1,Cancer Indicators,g1,"All cancer incidence rate per 100,000",5124.0,264241.0,Rate,646.4,NaN,NaN,NaN,NaN,2010-2012,"Cancer Registry Data as of April, 2015",NaN,NaN
1,North Country,1,Cancer Indicators,g1,"All cancer incidence rate per 100,000",5993.0,306231.0,Rate,652.3,NaN,NaN,NaN,NaN,2010-2012,"Cancer Registry Data as of April, 2015",NaN,NaN
2,Tug Hill Seaway,1,Cancer Indicators,g1,"All cancer incidence rate per 100,000",4034.0,257610.0,Rate,522.0,NaN,NaN,NaN,NaN,2010-2012,"Cancer Registry Data as of April, 2015",NaN,NaN
3,Central NY,1,Cancer Indicators,g1,"All cancer incidence rate per 100,000",18896.0,1025519.0,Rate,614.2,NaN,NaN,NaN,NaN,2010-2012,"Cancer Registry Data as of April, 2015",NaN,NaN
4,Southern Tier,1,Cancer Indicators,g1,"All cancer incidence rate per 100,000",8183.0,449813.0,Rate,606.4,NaN,NaN,NaN,NaN,2010-2012,"Cancer Registry Data as of April, 2015",NaN,NaN

In [4]:
obs_stats=health_stats[health_stats['Indicator']=='Age-adjusted percentage of adults obese (BMI 30 or higher)']

In [5]:
obs_stats.head()

,County Name,Health Topic Number,Health Topic,Indicator Number,Indicator,Event Count,Average Number of Denominator,Measure Unit,Percent/Rate,Lower Limit of 95% CI,Upper Limit of 95% CI,Data Comments,Quartile,Data Years,Data Source,Mapping Distribution,Location
4821,Albany,10,Obesity and Related Indicators,g75,Age-adjusted percentage of adults obese (BMI 3...,NaN,NaN,Percentage,26.0,21.8,30.1,NaN,0 - < 30.3 : Q1 & Q2,2013-2014,NYS Expanded Behavioral Risk Factor Surveillan...,1.0,"(42.678066, -73.814233)"
4822,Allegany,10,Obesity and Related Indicators,g75,Age-adjusted percentage of adults obese (BMI 3...,NaN,NaN,Percentage,30.6,23.9,37.4,NaN,30.3 - < 32.7 : Q3,2013-2014,NYS Expanded Behavioral Risk Factor Surveillan...,2.0,"(42.226801, -78.020567)"
4823,Broome,10,Obesity and Related Indicators,g75,Age-adjusted percentage of adults obese (BMI 3...,NaN,NaN,Percentage,31.7,26.0,37.3,NaN,30.3 - < 32.7 : Q3,2013-2014,NYS Expanded Behavioral Risk Factor Surveillan...,2.0,"(42.122015, -75.933191)"
4824,Cattaraugus,10,Obesity and Related Indicators,g75,Age-adjusted percentage of adults obese (BMI 3...,NaN,NaN,Percentage,33.5,27.1,40.0,NaN,32.7 + : Q4,2013-2014,NYS Expanded Behavioral Risk Factor Surveillan...,3.0,"(42.224267, -78.606673)"
4825,Cayuga,10,Obesity and Related Indicators,g75,Age-adjusted percentage of adults obese (BMI 3...,NaN,NaN,Percentage,33.0,24.8,41.1,NaN,32.7 + : Q4,2013-2014,NYS Expanded Behavioral Risk Factor Surveillan...,3.0,"(42.940095, -76.560755)"

In [6]:
obs_stats=obs_stats[['County Name','Indicator','Percent/Rate','Location']]
obs_stats=obs_stats.rename(columns={"County Name": "County", "Indicator": "Health_Topic","Percent/Rate":"Percentage"})
obs_stats.head()

,County,Health_Topic,Percentage,Location
4821,Albany,Age-adjusted percentage of adults obese (BMI 3...,26.0,"(42.678066, -73.814233)"
4822,Allegany,Age-adjusted percentage of adults obese (BMI 3...,30.6,"(42.226801, -78.020567)"
4823,Broome,Age-adjusted percentage of adults obese (BMI 3...,31.7,"(42.122015, -75.933191)"
4824,Cattaraugus,Age-adjusted percentage of adults obese (BMI 3...,33.5,"(42.224267, -78.606673)"
4825,Cayuga,Age-adjusted percentage of adults obese (BMI 3...,33.0,"(42.940095, -76.560755)"

In [7]:
obs_stats

,County,Health_Topic,Percentage,Location
4821,Albany,Age-adjusted percentage of adults obese (BMI 3...,26.0,"(42.678066, -73.814233)"
4822,Allegany,Age-adjusted percentage of adults obese (BMI 3...,30.6,"(42.226801, -78.020567)"
4823,Broome,Age-adjusted percentage of adults obese (BMI 3...,31.7,"(42.122015, -75.933191)"
4824,Cattaraugus,Age-adjusted percentage of adults obese (BMI 3...,33.5,"(42.224267, -78.606673)"
4825,Cayuga,Age-adjusted percentage of adults obese (BMI 3...,33.0,"(42.940095, -76.560755)"
...,...,...,...,...
4893,Central NY,Age-adjusted percentage of adults obese (BMI 3...,31.5,NaN
4894,Southern Tier,Age-adjusted percentage of adults obese (BMI 3...,29.8,NaN
4895,Finger Lakes,Age-adjusted percentage of adults obese (BMI 3...,27.2,NaN
4896,Western NY,Age-adjusted percentage of adults obese (BMI 3...,31.1,NaN
4897,New York State,Age-adjusted percentage of adults obese (BMI 3...,24.6,NaN

In [8]:
obs_stats=obs_stats[obs_stats['Location'].notna()]
obs_stats.shape

(62, 4)

In [9]:
obs_stats

,County,Health_Topic,Percentage,Location
4821,Albany,Age-adjusted percentage of adults obese (BMI 3...,26.0,"(42.678066, -73.814233)"
4822,Allegany,Age-adjusted percentage of adults obese (BMI 3...,30.6,"(42.226801, -78.020567)"
4823,Broome,Age-adjusted percentage of adults obese (BMI 3...,31.7,"(42.122015, -75.933191)"
4824,Cattaraugus,Age-adjusted percentage of adults obese (BMI 3...,33.5,"(42.224267, -78.606673)"
4825,Cayuga,Age-adjusted percentage of adults obese (BMI 3...,33.0,"(42.940095, -76.560755)"
...,...,...,...,...
4882,Bronx,Age-adjusted percentage of adults obese (BMI 3...,31.0,"(40.85589, -73.868294)"
4883,Kings,Age-adjusted percentage of adults obese (BMI 3...,24.8,"(40.65642, -73.950691)"
4884,New York,Age-adjusted percentage of adults obese (BMI 3...,16.8,"(40.726966, -74.005966)"
4885,Queens,Age-adjusted percentage of adults obese (BMI 3...,22.1,"(40.749338, -73.789673)"
4886,Richmond,Age-adjusted percentage of adults obese (BMI 3...,23.2,"(40.566763, -74.148102)"

In [10]:
NY_stats=obs_stats.to_json(orient='records')

with open('NY_Obs_Stats.json', 'w') as f:
    json.dump(NY_stats, f, indent=2)

In [11]:
geo_coord=obs_stats[['County','Location']]
geo_json=geo_coord.to_json(orient='records')

with open('Geo_Loc_Counties.json', 'w') as f:
    json.dump(geo_json, f, indent=2)